config/routes.rb
Rails.application.routes.draw do
  # /posts/1/comments/4
  resources :posts do
    resources :comments
  end
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :projects
  get 'projects', to:"projects#index"
  root 'main#main'
  devise_for :users
  get "home", to: 'home#index'
  resources :home
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
  # has_rich_text :body
  has_many_attached :pictures
end

app/models/post.rb
class Post < ApplicationRecord
    # after_destroy {notify admin of bad behavior}
    has_many :comments, dependent: :destroy
    validates :user_id, presence: true
    has_one_attached :image
    has_rich_text :body 
    
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :projects 
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :authenticate_user!
    before_action :set_post

    def create
        @comment = @post.comments.create(comment_params)
        @comment.user = current_user

        if @comment.save
            flash[:notice] = 'Comment has been created'
            redirect_to post_path(@post)
        else 
            flash[:alert] = 'Comment has not been created'
            redirect_to post_path(@post)
        end
    end

    def destroy
        @comment = @post.comments.find(params[:id])
        @comment.destroy
        redirect_to post_path(@post)

    end
    def update
        @comment = @post.comments.find(params[:id])
        respond_to do |format|
           if @comment.update(comment_params)
            format.html { redirect_to post_url(@post), notice: 'Successfully updated'}
           else
            format.html { redirect_to post_url(@post), alert: 'Failed to update successfully'}
           end
        end
    end
    private

    def set_post
        @post = Post.find(params[:post_id])
    end

    def comment_params
        params.require(:comment).permit(:content, :tasks, pictures: [])
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!
  def index
    # if current_user
    #   redirect_to main_path
    # end
    @projects = Project.all
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
    def main
      if user_signed_in?
        redirect_to posts_path
      end
    end
  end
  

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]
  before_action :set_user, only: %i[ index show edit update destroy ]
  before_action :authenticate_user!

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
    @post.update(views: @post.views + 1)
    @comments = Comment.all
    @posts = Post.all
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end
def set_user
  @users = User.all
end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :description, :body, :user_id, :image)
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  # GET /projects or /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1 or /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects or /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to project_url(@project), notice: "Project was successfully created." }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to project_url(@project), notice: "Project was successfully updated." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url, notice: "Project was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:name, :description, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/posts/show.html.erb
<head>

      <%= stylesheet_link_tag "posts", "data-turbo-track": "reload" %>
      <style>
        .btn_show{
          display:none;
        }
      </style>
</head>
<body>
<nav class="navbar navbar-expand-lg ">
  <!-- Container wrapper -->
  <div class="container-fluid">
    <!-- Navbar brand -->
    <a class="navbar-brand me-2" href="#">
      <svg style="height: 50px;vertical-align: middle;fill: currentColor;overflow: hidden;" viewBox="0 0 1024 1024" version="1.1" xmlns="http://www.w3.org/2000/svg"><path d="M668.8 967.68c-8.96 0-17.28-6.4-18.56-15.36l-51.84-257.92c-1.92-9.6 3.2-18.56 12.8-21.76 120.32-41.6 200.96-154.24 200.96-280.96 0-163.84-133.76-297.6-298.88-297.6-164.48 0-298.88 133.12-298.88 297.6 0 126.72 80.64 239.36 200.96 280.96 8.96 3.2 14.72 12.8 12.8 21.76l-51.84 257.92c-1.92 10.24-12.16 17.28-22.4 14.72-10.24-1.92-17.28-12.16-14.72-22.4l48.64-241.92c-126.72-51.2-211.2-174.08-211.2-311.68C175.36 206.08 326.4 55.68 512.64 55.68c185.6 0 337.28 150.4 337.28 336 0 137.6-83.84 260.48-211.2 311.68l48.64 241.92c1.92 10.24-4.48 20.48-14.72 22.4C671.36 967.68 670.08 967.68 668.8 967.68zM133.76 968.32c-1.28 0-2.56 0-3.84-0.64-10.24-1.92-17.28-12.16-14.72-22.4l33.92-167.04C58.88 740.48 0 652.8 0 554.88c0-113.92 78.08-211.84 189.44-236.8 10.24-2.56 20.48 3.84 23.04 14.72 2.56 10.24-3.84 20.48-14.72 23.04C103.68 376.32 38.4 458.88 38.4 554.88c0 87.04 55.68 165.12 138.24 193.92 8.96 3.2 14.72 12.8 12.8 21.76l-37.12 183.04C151.04 961.92 142.72 968.32 133.76 968.32zM890.24 968.32c-8.96 0-17.28-6.4-18.56-15.36l-37.12-183.04c-1.92-9.6 3.2-18.56 12.8-21.76 82.56-28.8 138.24-106.24 138.24-193.92 0-96-65.28-177.92-159.36-199.68-10.24-2.56-16.64-12.8-14.72-23.04s12.8-16.64 23.04-14.72c111.36 25.6 189.44 122.88 189.44 236.8 0 97.92-58.88 186.24-148.48 224l33.92 167.04c1.92 10.24-4.48 20.48-14.72 22.4C892.8 968.32 891.52 968.32 890.24 968.32zM512.64 581.76c-96.64 0-175.36-78.08-175.36-174.72 0-10.88 8.32-19.2 19.2-19.2s19.2 8.32 19.2 19.2c0 74.88 61.44 136.32 136.96 136.32 75.52 0 136.96-60.8 136.96-136.32 0-10.88 8.32-19.2 19.2-19.2s19.2 8.32 19.2 19.2C688 503.68 609.28 581.76 512.64 581.76z" /></svg>
    </a>

    <!-- Toggle button -->
    <button
      class="navbar-toggler"
      type="button"
      data-mdb-toggle="collapse"
      data-mdb-target="#navbarButtonsExample"
      aria-controls="navbarButtonsExample"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <i class="fas fa-bars"></i>
    </button>

    <!-- Collapsible wrapper -->
    <div class="collapse navbar-collapse" id="navbarButtonsExample">
      <!-- Left links -->
      <ul style="margin-left:50px;" class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item m-3">
          <%= link_to "Dashboard", posts_path, class:"navbar_item"%>
        </li>
        <li class="nav-item d-flex align-items-center m-3">
              <%= link_to "New Project", new_post_path, class:"navbar_item"%>
        </li>

        <li class="nav-item d-flex align-items-center m-3">
              <% link_to "Log out", destroy_user_session_path, method: :delete, class:"nav_item" %>
        </li>
        <li class="nav-item d-flex align-items-center m-3">
        </li>
      </ul>
      <!-- Left links -->

      <div class="d-flex align-items-center">
         
              <%= button_to 'log out', destroy_user_session_path, method: :delete, class:"button m-2 " %>
        
        
        <a
          class="nav_icon"
          href="https://github.com/Decta2/"
          role="button">
          <i class="fab fa-github"></i
        ></a>
      </div>
    </div>
    <!-- Collapsible wrapper -->
  </div>
  <!-- Container wrapper -->
</nav>
<p style="color: green"><%= notice %></p>
<header class="d-flex justify-content-center align-items-start">
    <div>
      <%= render @post %>
    </div>
    <div style="width:30%;" class="container card p-3 m-3">
        <%= render 'comments/form', 
        post: @post,
        comment: @post.comments.build,
        submit_label:"Reply" %>
      </div>
    <div style="width:30%;" class="card m-3 p-3 card_">
      <div>
        <% @comments.each do |comment|%>
            <%= render 'comments/post', 
            post: @post, 
            comment: comment %>
        <% end %>
      </div>
      <div> 
      <% if current_user.id == @post.user_id %>
          <div class="mt-2">
            <%= link_to "Edit this post", edit_post_path(@post) %><i class="fa-solid fa-pen-to-square m-1"></i> |
            <%= link_to "Back to posts", posts_path %><i class="fa-solid fa-arrow-right-from-bracket m-1"></i>
          </div>
          <%= button_to "Destroy this post", @post, class:"btn btn-primary mt-3", method: :delete %>
      <% else %>
          <div class="back">
            <%= link_to "Back to posts", posts_path %> <i class="fa-solid fa-arrow-right-from-bracket m-1"></i>
          </div>
      <% end %>
  </div>
    </div>
</header>
</body>

app/views/projects/new.html.erb
<head>
  <style>
    @import url('https://fonts.googleapis.com/css2?family=Montserrat:wght@300&display=swap');
      *{
        font-family: 'Montserrat', sans-serif;
      }
      .navbar{
          background-color:rgba(42, 124, 238, 0.2);
          color:#53ffff;

      }
      h1,h2,h3,h4,h5,h6{
            color:#5effff;
            text-align:center;
      }
      .navbar svg{
        color:#098dc6;
      }
      #card_project{
              background-color:rgba(100, 230, 253, 0.3);
              color:#5effff;
              position: relative;
      }
      #myVideo{
            position: fixed;
            z-index: -1;
            right: 0;
            bottom: 0;
        }
        .input{
          background:rgba(132, 248, 248, 0.2);
          border: 1px solid #5effff;
          color:#5effff;
        }
        @media (min-aspect-ratio: 16/9){
            #myVideo{
                width: 100%;
                height: auto;
            }
        }
        @media (max-aspect-ratio: 16/9){
            #myVideo{
                width: auto;
                height: 100%;   
            }
        }
        
        .button{
            text-decoration:none;
            text-transform:uppercase;
            padding: 10px 15px;
            border: 1px solid #5effff;
            background:rgba(132, 248, 248, 0.0);
            font-size:14px;
            border-radius:10px;
            color:#5effff;
            font-family: 'Montserrat', sans-serif;
            transition: 0.5s ease;
        }
        .button:hover{
            color:#fff;
            background:rgba(132, 248, 248, 0.2);
        }
        a{
          text-decoration:none;
          font-family: 'Montserrat', sans-serif;  
          color:#5effff;
        }
        a:hover{
          color:lightblue;
        }
        .navbar_item{
          text-decoration:none; 
          color:#098dc6;
        }
        .navbar_item:hover{
          color:#5effff;
        }
        .nav_icon{
          border:1px solid #098dc6;
          color:#098dc6;
          border-radius:5px;
          background:none;
          padding:5px 10px;
        }
        .nav_icon:hover{
          border:1px solid #5effff;
          color:#5effff;
          background:rgba(132, 248, 248, 0.2);
        }
  </style>
</head>
<body>
<nav class="navbar navbar-expand-lg ">
  <!-- Container wrapper -->
  <div class="container-fluid">
    <!-- Navbar brand -->
    <a class="navbar-brand me-2" href="#">
      <svg style="height: 50px;vertical-align: middle;fill: currentColor;overflow: hidden;" viewBox="0 0 1024 1024" version="1.1" xmlns="http://www.w3.org/2000/svg"><path d="M668.8 967.68c-8.96 0-17.28-6.4-18.56-15.36l-51.84-257.92c-1.92-9.6 3.2-18.56 12.8-21.76 120.32-41.6 200.96-154.24 200.96-280.96 0-163.84-133.76-297.6-298.88-297.6-164.48 0-298.88 133.12-298.88 297.6 0 126.72 80.64 239.36 200.96 280.96 8.96 3.2 14.72 12.8 12.8 21.76l-51.84 257.92c-1.92 10.24-12.16 17.28-22.4 14.72-10.24-1.92-17.28-12.16-14.72-22.4l48.64-241.92c-126.72-51.2-211.2-174.08-211.2-311.68C175.36 206.08 326.4 55.68 512.64 55.68c185.6 0 337.28 150.4 337.28 336 0 137.6-83.84 260.48-211.2 311.68l48.64 241.92c1.92 10.24-4.48 20.48-14.72 22.4C671.36 967.68 670.08 967.68 668.8 967.68zM133.76 968.32c-1.28 0-2.56 0-3.84-0.64-10.24-1.92-17.28-12.16-14.72-22.4l33.92-167.04C58.88 740.48 0 652.8 0 554.88c0-113.92 78.08-211.84 189.44-236.8 10.24-2.56 20.48 3.84 23.04 14.72 2.56 10.24-3.84 20.48-14.72 23.04C103.68 376.32 38.4 458.88 38.4 554.88c0 87.04 55.68 165.12 138.24 193.92 8.96 3.2 14.72 12.8 12.8 21.76l-37.12 183.04C151.04 961.92 142.72 968.32 133.76 968.32zM890.24 968.32c-8.96 0-17.28-6.4-18.56-15.36l-37.12-183.04c-1.92-9.6 3.2-18.56 12.8-21.76 82.56-28.8 138.24-106.24 138.24-193.92 0-96-65.28-177.92-159.36-199.68-10.24-2.56-16.64-12.8-14.72-23.04s12.8-16.64 23.04-14.72c111.36 25.6 189.44 122.88 189.44 236.8 0 97.92-58.88 186.24-148.48 224l33.92 167.04c1.92 10.24-4.48 20.48-14.72 22.4C892.8 968.32 891.52 968.32 890.24 968.32zM512.64 581.76c-96.64 0-175.36-78.08-175.36-174.72 0-10.88 8.32-19.2 19.2-19.2s19.2 8.32 19.2 19.2c0 74.88 61.44 136.32 136.96 136.32 75.52 0 136.96-60.8 136.96-136.32 0-10.88 8.32-19.2 19.2-19.2s19.2 8.32 19.2 19.2C688 503.68 609.28 581.76 512.64 581.76z" /></svg>
    </a>

    <!-- Toggle button -->
    <button
      class="navbar-toggler"
      type="button"
      data-mdb-toggle="collapse"
      data-mdb-target="#navbarButtonsExample"
      aria-controls="navbarButtonsExample"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <i class="fas fa-bars"></i>
    </button>

    <!-- Collapsible wrapper -->
    <div class="collapse navbar-collapse" id="navbarButtonsExample">
      <!-- Left links -->
      <ul style="margin-left:50px;" class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item m-3">
          <%= link_to "Dashboard", projects_path, class:"navbar_item"%>
        </li>
        <li class="nav-item d-flex align-items-center m-3">
              <%= link_to "New project B1", new_project_path, class:"navbar_item"%>
        </li>
        <li class="nav-item d-flex align-items-center m-3">
              <%= link_to "Projects B2", posts_path, class:"navbar_item"%>
        </li>

        <li class="nav-item d-flex align-items-center m-3">
              <% link_to "Log out", destroy_user_session_path, method: :delete, class:"nav_item" %>
        </li>
      </ul>
      <!-- Left links -->

      <div class="d-flex align-items-center">
         
              <%= button_to 'log out', destroy_user_session_path, method: :delete, class:"button m-2 " %>
        
        
        <a
          class="nav_icon"
          href="https://github.com/Decta2/"
          role="button">
          <i class="fab fa-github"></i
        ></a>
      </div>
    </div>
    <!-- Collapsible wrapper -->
  </div>
  <!-- Container wrapper -->
</nav>

<div style="width:100%; height: 90vh;" class="d-flex align-items-center justify-content-center">
  <div id="card_project" class="card p-3">
      <h1>New project</h1>

      <%= render "form", project: @project %>

      <br>

      <div  style="text-align:center;" >
        <%= link_to "Back to projects", projects_path %>
      </div>
  </div>
</div>
<%= video_tag "home.mp4", autoplay: :autoplay, loop: :loop, id:"myVideo", class:"myVideo", style:"position: fixed; z-index: -1; right: 0; bottom: 0;" %>

</body>

app/views/projects/show.html.erb
<head>
  <style>
    @import url('https://fonts.googleapis.com/css2?family=Montserrat:wght@300&display=swap');
      *{
        font-family: 'Montserrat', sans-serif;
      }
      .navbar{
          background-color:rgba(42, 124, 238, 0.2);
          color:#53ffff;

      }
      h1,h2,h3,h4,h5,h6{
            color:#098dc6;
      }
      .navbar svg{
        color:#098dc6;
      }
      #card_project{
              background-color:rgba(100, 230, 253, 0.3);
              color:#5effff;
              position: relative;
      }
      #myVideo{
            position: fixed;
            z-index: -1;
            right: 0;
            bottom: 0;
        }
        .input{
          background:rgba(132, 248, 248, 0.2);
          border: 1px solid #5effff;
          color:#5effff;
        }
        @media (min-aspect-ratio: 16/9){
            #myVideo{
                width: 100%;
                height: auto;
            }
        }
        @media (max-aspect-ratio: 16/9){
            #myVideo{
                width: auto;
                height: 100%;   
            }
        }
        
        .button{
            text-decoration:none;
            text-transform:uppercase;
            padding: 5px 10px;
            border: 1px solid #5effff;
            background:rgba(132, 248, 248, 0.0);
            font-size:14px;
            border-radius:10px;
            color:#5effff;
            transition: 0.5s ease;
        }
        .destroy{
            animation: mymove 1s infinite;
        }
        @keyframes mymove {
          0% {background:none}
          25% {background:rgba(132, 248, 248, 0.4)}
          50% {background:rgba(132, 248, 248, 0.8)}
          75% {background:rgba(132, 248, 248, 0.4)}
          100% {background:none}
        }
        a{
          text-decoration:none;
          color:#5effff;
        }
        a:hover{
          color:lightblue;
        }
        .navbar_item{
          text-decoration:none; 
          color:#098dc6;
        }
        .navbar_item:hover{
          color:#5effff;
        }
        .nav_icon{
          border:1px solid #098dc6;
          color:#098dc6;
          border-radius:5px;
          background:none;
          padding:5px 10px;
        }
        .nav_icon:hover{
          border:1px solid #5effff;
          color:#5effff;
          background:rgba(132, 248, 248, 0.2);
        }
        .card_project{
          width:100%;
        }
  </style>
</head>
<body>
<nav class="navbar navbar-expand-lg ">
  <!-- Container wrapper -->
  <div class="container-fluid">
    <!-- Navbar brand -->
    <a class="navbar-brand me-2" href="#">
      <svg style="height: 50px;vertical-align: middle;fill: currentColor;overflow: hidden;" viewBox="0 0 1024 1024" version="1.1" xmlns="http://www.w3.org/2000/svg"><path d="M668.8 967.68c-8.96 0-17.28-6.4-18.56-15.36l-51.84-257.92c-1.92-9.6 3.2-18.56 12.8-21.76 120.32-41.6 200.96-154.24 200.96-280.96 0-163.84-133.76-297.6-298.88-297.6-164.48 0-298.88 133.12-298.88 297.6 0 126.72 80.64 239.36 200.96 280.96 8.96 3.2 14.72 12.8 12.8 21.76l-51.84 257.92c-1.92 10.24-12.16 17.28-22.4 14.72-10.24-1.92-17.28-12.16-14.72-22.4l48.64-241.92c-126.72-51.2-211.2-174.08-211.2-311.68C175.36 206.08 326.4 55.68 512.64 55.68c185.6 0 337.28 150.4 337.28 336 0 137.6-83.84 260.48-211.2 311.68l48.64 241.92c1.92 10.24-4.48 20.48-14.72 22.4C671.36 967.68 670.08 967.68 668.8 967.68zM133.76 968.32c-1.28 0-2.56 0-3.84-0.64-10.24-1.92-17.28-12.16-14.72-22.4l33.92-167.04C58.88 740.48 0 652.8 0 554.88c0-113.92 78.08-211.84 189.44-236.8 10.24-2.56 20.48 3.84 23.04 14.72 2.56 10.24-3.84 20.48-14.72 23.04C103.68 376.32 38.4 458.88 38.4 554.88c0 87.04 55.68 165.12 138.24 193.92 8.96 3.2 14.72 12.8 12.8 21.76l-37.12 183.04C151.04 961.92 142.72 968.32 133.76 968.32zM890.24 968.32c-8.96 0-17.28-6.4-18.56-15.36l-37.12-183.04c-1.92-9.6 3.2-18.56 12.8-21.76 82.56-28.8 138.24-106.24 138.24-193.92 0-96-65.28-177.92-159.36-199.68-10.24-2.56-16.64-12.8-14.72-23.04s12.8-16.64 23.04-14.72c111.36 25.6 189.44 122.88 189.44 236.8 0 97.92-58.88 186.24-148.48 224l33.92 167.04c1.92 10.24-4.48 20.48-14.72 22.4C892.8 968.32 891.52 968.32 890.24 968.32zM512.64 581.76c-96.64 0-175.36-78.08-175.36-174.72 0-10.88 8.32-19.2 19.2-19.2s19.2 8.32 19.2 19.2c0 74.88 61.44 136.32 136.96 136.32 75.52 0 136.96-60.8 136.96-136.32 0-10.88 8.32-19.2 19.2-19.2s19.2 8.32 19.2 19.2C688 503.68 609.28 581.76 512.64 581.76z" /></svg>
    </a>

    <!-- Toggle button -->
    <button
      class="navbar-toggler"
      type="button"
      data-mdb-toggle="collapse"
      data-mdb-target="#navbarButtonsExample"
      aria-controls="navbarButtonsExample"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <i class="fas fa-bars"></i>
    </button>

    <!-- Collapsible wrapper -->
    <div class="collapse navbar-collapse" id="navbarButtonsExample">
      <!-- Left links -->
      <ul style="margin-left:50px;" class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item m-3">
          <%= link_to "Dashboard", projects_path, class:"navbar_item"%>
        </li>
        <li class="nav-item d-flex align-items-center m-3">
              <%= link_to "New project B1", new_project_path, class:"navbar_item"%>
        </li>
        <li class="nav-item d-flex align-items-center m-3">
              <%= link_to "Projects B2", posts_path, class:"navbar_item"%>
        </li>

        <li class="nav-item d-flex align-items-center m-3">
              <% link_to "Log out", destroy_user_session_path, method: :delete, class:"nav_item" %>
        </li>
      </ul>
      <!-- Left links -->

      <div class="d-flex align-items-center">
         
              <%= button_to 'log out', destroy_user_session_path, method: :delete, class:"button m-2 " %>
        
        
        <a
          class="nav_icon"
          href="https://github.com/Decta2/"
          role="button">
          <i class="fab fa-github"></i
        ></a>
      </div>
    </div>
    <!-- Collapsible wrapper -->
  </div>
  <!-- Container wrapper -->
</nav>

<p style="color: green;"><%= notice %></p>
<div style="width:100%; height: 90vh;" class="d-flex align-items-center justify-content-center">
  <div style="text-align:center;" id="card_project" class="card p-3">
<%= render @project %>

      <div>
        <%= link_to "Edit this project", edit_project_path(@project)%> |
        <%= link_to "Back to projects", projects_path %>
        <%= button_to "Destroy this project", @project, method: :delete, class:"button destroy mt-3" %>
      </div>
  </div>
</div>
<%= video_tag "home.mp4", autoplay: :autoplay, loop: :loop, id:"myVideo", class:"myVideo", style:"position: fixed; z-index: -1; right: 0; bottom: 0;" %>
</body>